"""Approved Enrichment Layer for Commercial Catalog Snapshot (CCS-001 / CCS-002).

Provides deterministic enrichment metadata keyed strictly by canonical_id.
Enrichment adds customer experience attributes (benefits, audience, goals, approved summaries,
aliases, safe CTAs, external provider IDs) without overriding WooCommerce transactional truth.
"""

from __future__ import annotations

from typing import Any

# Approved canonical enrichment definitions keyed strictly by canonical_id
APPROVED_ENRICHMENT_REGISTRY: dict[str, dict[str, Any]] = {
    # -------------------------------------------------------------------------
    # CONSULTATION SERVICE
    # -------------------------------------------------------------------------
    "ccc:service:is-cannabis-right-for-me": {
        "canonical_id": "ccc:service:is-cannabis-right-for-me",
        "entity_type": "SERVICE",
        "brand": "Wake'n'Bake Lounge",
        "category": ["Education", "Consultation", "Wellness"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 75.0,
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Personalized 1-on-1 cannabis educational consultation ($75) with Budly T. Cannaguide.",
        "description": "A dedicated, one-on-one educational consultation with Budly T. Cannaguide to discuss cannabis fundamentals, cannabinoid education, consumption methods, and answer your questions in a supportive, judgment-free environment.",
        "benefits": [
            "1-on-1 personalized educational consultation with Budly T. Cannaguide",
            "Personalized cannabinoid & terpene guidance",
            "Custom consumption method recommendations",
            "Curated product roadmap tailored to your wellness goals",
            "Follow-up educational resources & links",
        ],
        "audience": ["Cannabis beginners", "Wellness seekers", "Curious adults exploring hemp & CBD"],
        "customer_goals": [
            "Understand if cannabis or CBD fits personal wellness",
            "Learn responsible dosing fundamentals",
            "Get personalized product recommendations",
        ],
        "eligibility_rules": ["Must be 21+ or have valid state medical recommendation"],
        "exclusions": ["Not medical advice, diagnosis, treatment, or prescription"],
        "fulfillment_type": "CONSULTATION_SERVICE",
        "fulfillment_platform": "WIX_BOOKINGS",
        "canonical_url": "https://wakenbakelounge.com/service-page/is-cannabis-right-for-me",
        "checkout_url": "https://wakenbakelounge.com/service-page/is-cannabis-right-for-me",
        "booking_url": "https://wakenbakelounge.com/service-page/is-cannabis-right-for-me",
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "WIX_BOOKINGS",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": None,
        "source_authority": "wix_bookings",
        "aliases": [
            "is cannabis right for me",
            "cannabis consultation",
            "1-on-1 consultation",
            "consultation",
            "book a consultation",
            "consult with budly",
        ],
    },

    # -------------------------------------------------------------------------
    # COMMUNITY MEMBERSHIPS (UNRELEASED / APPROVED_NOT_RELEASED)
    # -------------------------------------------------------------------------
    "wnb:community:lounge-pass": {
        "canonical_id": "wnb:community:lounge-pass",
        "entity_type": "COMMUNITY_MEMBERSHIP",
        "brand": "Wake'n'Bake Lounge",
        "category": ["Membership", "Community"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "APPROVED_NOT_RELEASED",
        "customer_purchasable": False,
        "catalog_visibility": "hidden",
        "stock_status": "not_applicable",
        "price_usd": 0.0,
        "currency": "USD",
        "billing_model": "FREE",
        "short_summary": "Free community access to Wake'n'Bake Lounge (approved for future launch; currently unreleased).",
        "description": "Free community access to Wake'n'Bake Lounge platform. Join discussions, read curated recipes, and explore educational content.",
        "benefits": [
            "Community access",
        ],
        "audience": ["Cannabis community members", "Culinary enthusiasts"],
        "customer_goals": ["Access free community resources and forum discussions"],
        "eligibility_rules": ["21+ age verification"],
        "exclusions": ["Does not include store discounts or priority event access"],
        "fulfillment_type": "MEMBERSHIP_ACCESS",
        "fulfillment_platform": "WIX_PLANS",
        "canonical_url": "https://wakenbakelounge.com/plans-pricing",
        "checkout_url": None,
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "NONE",
        "coupon_relationship": None,
        "wix_plan_id": "a101970a-4600-4dbb-8e49-e91cfed93d80",
        "wordpress_page_id": 1050,
        "source_authority": "owner_approved_specification",
        "aliases": [
            "lounge pass",
            "wake'n'bake lounge pass",
            "free pass",
            "free community membership",
        ],
    },

    "wnb:community:lounge-member": {
        "canonical_id": "wnb:community:lounge-member",
        "entity_type": "COMMUNITY_MEMBERSHIP",
        "brand": "Wake'n'Bake Lounge",
        "category": ["Membership", "Community"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "APPROVED_NOT_RELEASED",
        "customer_purchasable": False,
        "catalog_visibility": "hidden",
        "stock_status": "not_applicable",
        "price_usd": 9.99,
        "currency": "USD",
        "billing_model": "RECURRING_MONTHLY",
        "short_summary": "Wake'n'Bake Lounge Member ($9.99/mo) with 10% discount on Lounge Collection products.",
        "description": "Join the premium Wake'n'Bake Lounge community for $9.99/month. Enjoy 10% off all Lounge Collection products, early access to new drops, exclusive forum sections, member badge, and priority event access.",
        "benefits": [
            "Community access",
            "10% off all Lounge Collection products",
            "Early access to new drops",
            "Exclusive forum sections",
            "Member badge",
            "Priority event access",
        ],
        "audience": ["Active Wake'n'Bake community members", "Frequent Lounge Collection shoppers"],
        "customer_goals": [
            "Save 10% on Lounge Collection orders",
            "Get early drop alerts",
            "Access exclusive member forums",
        ],
        "eligibility_rules": ["Active monthly subscription"],
        "exclusions": ["Discounts apply only to Lounge Collection products"],
        "fulfillment_type": "MEMBERSHIP_ACCESS",
        "fulfillment_platform": "WIX_PLANS",
        "canonical_url": "https://wakenbakelounge.com/plans-pricing",
        "checkout_url": None,
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "TBD_APPROVED_PROCESSOR",
        "coupon_relationship": "LOUNGEMEMBER10",
        "wix_plan_id": "1658a089-db78-418c-85ed-ac01d5bcabb0",
        "wordpress_page_id": 1051,
        "source_authority": "owner_approved_specification",
        "aliases": [
            "lounge member",
            "wake'n'bake lounge member",
            "lounge membership",
            "monthly lounge member",
        ],
    },

    "wnb:community:lounge-elite": {
        "canonical_id": "wnb:community:lounge-elite",
        "entity_type": "COMMUNITY_MEMBERSHIP",
        "brand": "Wake'n'Bake Lounge",
        "category": ["Membership", "Community"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "APPROVED_NOT_RELEASED",
        "customer_purchasable": False,
        "catalog_visibility": "hidden",
        "stock_status": "not_applicable",
        "price_usd": 24.99,
        "currency": "USD",
        "billing_model": "RECURRING_MONTHLY",
        "short_summary": "Wake'n'Bake Lounge Elite ($24.99/mo) with 25% discount, VIP badge, and curated content.",
        "description": "The premium Wake'n'Bake Lounge membership tier for $24.99/month. Enjoy 25% off all Lounge Collection products, first access to exclusive drops, VIP forum badge, priority event invitations, and monthly curated content from Budly T. Cannaguide.",
        "benefits": [
            "Community access",
            "25% off all Lounge Collection products",
            "First access to exclusive drops",
            "VIP forum badge",
            "Priority event invitations",
            "Monthly curated content from Budly T. Cannaguide",
        ],
        "audience": ["Dedicated cannabis aficionados", "VIP community members"],
        "customer_goals": [
            "Maximize savings with 25% Lounge Collection discount",
            "First access to limited drops",
            "Exclusive curated guidance from Budly",
        ],
        "eligibility_rules": ["Active monthly subscription"],
        "exclusions": ["Discounts apply only to Lounge Collection products"],
        "fulfillment_type": "MEMBERSHIP_ACCESS",
        "fulfillment_platform": "WIX_PLANS",
        "canonical_url": "https://wakenbakelounge.com/plans-pricing",
        "checkout_url": None,
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "TBD_APPROVED_PROCESSOR",
        "coupon_relationship": "LOUNGEELITE25",
        "wix_plan_id": "ac8a8d86-961d-417e-84a3-47cd6537db9f",
        "wordpress_page_id": 1052,
        "source_authority": "owner_approved_specification",
        "aliases": [
            "lounge elite",
            "wake'n'bake lounge elite",
            "elite member",
            "vip lounge membership",
        ],
    },

    # -------------------------------------------------------------------------
    # BOOKS
    # -------------------------------------------------------------------------
    "ccc:book:infused-basics": {
        "canonical_id": "ccc:book:infused-basics",
        "entity_type": "BOOK",
        "brand": "Compassionate Care Cultivators",
        "category": ["Book", "Culinary", "Education"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 40.0,
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Infused Basics: The Beginner's Guide to Infuse Everything Edible ($40.00).",
        "description": "The foundational culinary cannabis book by Compassionate Care Cultivators. Covers infusion principles, decarboxylation, dosage calculations, and delicious starter recipes.",
        "benefits": [
            "Complete beginner guide to cannabis infusions and decarboxylation",
            "Step-by-step recipes for oils, butters, and edibles",
            "Accurate dosage calculation tables",
            "Companion culinary resource for kitchen novices and pros",
        ],
        "audience": ["Home cooks", "Edible enthusiasts", "Culinary beginners"],
        "customer_goals": [
            "Learn to make homemade cannabis butter and oils",
            "Calculate precise edible dosages",
            "Master basic infusion recipes",
        ],
        "eligibility_rules": ["21+ or valid state authorization"],
        "exclusions": ["This is a physical/digital book, NOT a structured online course"],
        "fulfillment_type": "PHYSICAL_SHIPPING",
        "fulfillment_platform": "WOOCOMMERCE",
        "canonical_url": "https://cccultivate.com/product/infused-basics/",
        "checkout_url": "https://cccultivate.com/cart/?add-to-cart=87",
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "WOOCOMMERCE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 87,
        "source_authority": "woocommerce",
        "aliases": [
            "infused basics",
            "infused basics book",
            "beginner guide to infuse everything edible",
            "infuse everything edible",
            "cooking book",
            "cannabis recipe book",
        ],
    },

    "ccc:book:botanical-collection-v1": {
        "canonical_id": "ccc:book:botanical-collection-v1",
        "entity_type": "BOOK",
        "brand": "Compassionate Care Cultivators",
        "category": ["Book", "Education", "Art"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 14.99,
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Cannabis Botanical Collection Vol. 1 ($14.99) botanical guide and coloring collection.",
        "description": "A curated collection of botanical cannabis illustrations, anatomy diagrams, and educational coloring pages.",
        "benefits": [
            "Detailed botanical cannabis illustrations",
            "Plant anatomy education and coloring pages",
        ],
        "audience": ["Art lovers", "Botanical enthusiasts", "Mindful cannabis learners"],
        "customer_goals": ["Enjoy botanical art and learn plant morphology"],
        "eligibility_rules": ["Open to all adults 21+"],
        "exclusions": [],
        "fulfillment_type": "PHYSICAL_SHIPPING",
        "fulfillment_platform": "WOOCOMMERCE",
        "canonical_url": "https://cccultivate.com/product/cannabis-botanical-collection-vol-1/",
        "checkout_url": "https://cccultivate.com/cart/?add-to-cart=88",
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "WOOCOMMERCE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 88,
        "source_authority": "woocommerce",
        "aliases": [
            "botanical collection",
            "cannabis botanical collection",
            "coloring book",
            "botanical collection vol 1",
        ],
    },

    # -------------------------------------------------------------------------
    # STRUCTURED COURSES & PAYMENT PLANS
    # -------------------------------------------------------------------------
    "ccc:course:culinary-cannabis": {
        "canonical_id": "ccc:course:culinary-cannabis",
        "entity_type": "COURSE",
        "brand": "Compassionate Care Cultivators",
        "category": ["Course", "Culinary", "Education"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 1000.0,
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Culinary Cannabis structured online masterclass ($1,000 one-time).",
        "description": "Comprehensive culinary cannabis masterclass covering gourmet infusions, lipid science, precision dosing, and professional kitchen techniques.",
        "benefits": [
            "Full access to the Culinary Cannabis masterclass curriculum",
            "Advanced lipid extraction & infusion techniques",
            "Precision dosing & lab-testing comprehension",
            "Certificate of completion from Compassionate Care Cultivators",
        ],
        "audience": ["Aspiring cannabis chefs", "Edible creators", "Culinary professionals"],
        "customer_goals": ["Master gourmet cannabis cooking and commercial infusion standards"],
        "eligibility_rules": ["21+ required"],
        "exclusions": [],
        "fulfillment_type": "DIGITAL_DELIVERY",
        "fulfillment_platform": "WOOCOMMERCE",
        "canonical_url": "https://cccultivate.com/product/culinary-cannabis/",
        "checkout_url": "https://cccultivate.com/cart/?add-to-cart=150",
        "booking_url": None,
        "payment_plan_available": True,
        "payment_plan_amount": 300.0,
        "payment_plan_url": "https://cccultivate.com/product/culinary-cannabis-payment-plan/",
        "payment_processor": "WOOCOMMERCE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 150,
        "source_authority": "woocommerce",
        "aliases": [
            "culinary cannabis",
            "culinary cannabis course",
            "cooking class",
            "culinary masterclass",
            "cooking course",
        ],
    },

    "ccc:course:culinary-cannabis:payment-plan": {
        "canonical_id": "ccc:course:culinary-cannabis:payment-plan",
        "entity_type": "COURSE_PAYMENT_PLAN",
        "brand": "Compassionate Care Cultivators",
        "category": ["Course", "Payment Plan", "Culinary"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 300.0,
        "currency": "USD",
        "billing_model": "INSTALLMENT",
        "short_summary": "Culinary Cannabis 4-Month Installment Payment Plan ($300/mo via Stripe).",
        "description": "Flexible 4-month installment payment plan for the Culinary Cannabis masterclass ($300/month).",
        "benefits": [
            "Immediate access to Culinary Cannabis course content",
            "Spread tuition across monthly installments",
        ],
        "audience": ["Culinary students seeking flexible monthly payments"],
        "customer_goals": ["Enroll in Culinary Cannabis with monthly budgeting"],
        "eligibility_rules": ["Valid credit card for recurring monthly billing"],
        "exclusions": [],
        "fulfillment_type": "DIGITAL_DELIVERY",
        "fulfillment_platform": "STRIPE",
        "canonical_url": "https://cccultivate.com/product/culinary-cannabis-payment-plan/",
        "checkout_url": "https://buy.stripe.com/cNi3cugI527OeoS9BleIw0J",
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "STRIPE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 455,
        "source_authority": "woocommerce_external",
        "aliases": [
            "culinary cannabis payment plan",
            "culinary installment plan",
            "culinary cannabis 300",
        ],
    },

    "ccc:course:grow-cannabis-home": {
        "canonical_id": "ccc:course:grow-cannabis-home",
        "entity_type": "COURSE",
        "brand": "Compassionate Care Cultivators",
        "category": ["Course", "Cultivation", "Education"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 1500.0,
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Grow Cannabis @ Home structured cultivation masterclass ($1,500 one-time).",
        "description": "Complete indoor and outdoor home cultivation course. Covers genetics, lighting, nutrients, canopy management, harvesting, and curing.",
        "benefits": [
            "Complete seed-to-harvest cultivation training",
            "Environment, lighting, and nutrient optimization guides",
            "Pest management & organic growing protocols",
            "Direct instructor guidance and harvest troubleshooting",
        ],
        "audience": ["Home growers", "Caregivers", "Horticulture enthusiasts"],
        "customer_goals": ["Successfully grow clean, high-yield cannabis at home"],
        "eligibility_rules": ["21+ and compliant with local cultivation regulations"],
        "exclusions": [],
        "fulfillment_type": "DIGITAL_DELIVERY",
        "fulfillment_platform": "WOOCOMMERCE",
        "canonical_url": "https://cccultivate.com/product/grow-cannabis-home/",
        "checkout_url": "https://cccultivate.com/cart/?add-to-cart=151",
        "booking_url": None,
        "payment_plan_available": True,
        "payment_plan_amount": 425.0,
        "payment_plan_url": "https://cccultivate.com/product/grow-cannabis-home-payment-plan/",
        "payment_processor": "WOOCOMMERCE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 151,
        "source_authority": "woocommerce",
        "aliases": [
            "grow cannabis home",
            "grow cannabis @ home",
            "growing class",
            "cultivation course",
            "grow class",
            "learn to grow",
        ],
    },

    "ccc:course:grow-cannabis-home:payment-plan": {
        "canonical_id": "ccc:course:grow-cannabis-home:payment-plan",
        "entity_type": "COURSE_PAYMENT_PLAN",
        "brand": "Compassionate Care Cultivators",
        "category": ["Course", "Payment Plan", "Cultivation"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 425.0,
        "currency": "USD",
        "billing_model": "INSTALLMENT",
        "short_summary": "Grow Cannabis @ Home 4-Month Installment Payment Plan ($425/mo via Stripe).",
        "description": "Flexible 4-month installment payment plan for Grow Cannabis @ Home ($425/month).",
        "benefits": [
            "Immediate access to Grow Cannabis @ Home course curriculum",
            "Spread tuition across monthly installments",
        ],
        "audience": ["Growers seeking flexible monthly payments"],
        "customer_goals": ["Enroll in Grow Cannabis @ Home with monthly installments"],
        "eligibility_rules": ["Valid credit card for recurring billing"],
        "exclusions": [],
        "fulfillment_type": "DIGITAL_DELIVERY",
        "fulfillment_platform": "STRIPE",
        "canonical_url": "https://cccultivate.com/product/grow-cannabis-home-payment-plan/",
        "checkout_url": "https://buy.stripe.com/14A7sKfE113KbcG14PeIw0K",
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "STRIPE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 457,
        "source_authority": "woocommerce_external",
        "aliases": [
            "grow cannabis home payment plan",
            "grow installment plan",
            "grow course payment plan",
        ],
    },

    "ccc:course:grow-cook-with-me": {
        "canonical_id": "ccc:course:grow-cook-with-me",
        "entity_type": "COURSE",
        "brand": "Compassionate Care Cultivators",
        "category": ["Course", "Bundle", "Education"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 2500.0,
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Cook & Grow With Me comprehensive dual masterclass bundle ($2,500 one-time).",
        "description": "Complete dual masterclass combining both Grow Cannabis @ Home and Culinary Cannabis into one comprehensive curriculum.",
        "benefits": [
            "Full access to both Grow Cannabis @ Home and Culinary Cannabis",
            "Comprehensive seed-to-table cannabis mastery",
            "Save $500 compared to enrolling in both courses separately",
            "Priority instructor access and dual certifications",
        ],
        "audience": ["Dedicated craft cultivators and edible creators", "Commercial entrepreneurs"],
        "customer_goals": ["Master both cultivation and culinary infusion disciplines"],
        "eligibility_rules": ["21+ required"],
        "exclusions": [],
        "fulfillment_type": "DIGITAL_DELIVERY",
        "fulfillment_platform": "WOOCOMMERCE",
        "canonical_url": "https://cccultivate.com/product/cook-grow-with-me/",
        "checkout_url": "https://cccultivate.com/cart/?add-to-cart=152",
        "booking_url": None,
        "payment_plan_available": True,
        "payment_plan_amount": 675.0,
        "payment_plan_url": "https://cccultivate.com/product/cook-grow-with-me-payment-plan/",
        "payment_processor": "WOOCOMMERCE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 152,
        "source_authority": "woocommerce",
        "aliases": [
            "cook and grow with me",
            "cook & grow with me",
            "grow cook with me",
            "dual course bundle",
            "both classes",
        ],
    },

    "ccc:course:grow-cook-with-me:payment-plan": {
        "canonical_id": "ccc:course:grow-cook-with-me:payment-plan",
        "entity_type": "COURSE_PAYMENT_PLAN",
        "brand": "Compassionate Care Cultivators",
        "category": ["Course", "Payment Plan", "Bundle"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 675.0,
        "currency": "USD",
        "billing_model": "INSTALLMENT",
        "short_summary": "Cook & Grow With Me 4-Month Installment Payment Plan ($675/mo via Stripe).",
        "description": "Flexible 4-month installment payment plan for the Cook & Grow With Me dual bundle ($675/month).",
        "benefits": [
            "Immediate access to both Grow Cannabis @ Home and Culinary Cannabis",
            "Spread tuition across monthly installments",
        ],
        "audience": ["Students seeking dual bundle enrollment with monthly payments"],
        "customer_goals": ["Enroll in Cook & Grow With Me with monthly installments"],
        "eligibility_rules": ["Valid credit card for recurring billing"],
        "exclusions": [],
        "fulfillment_type": "DIGITAL_DELIVERY",
        "fulfillment_platform": "STRIPE",
        "canonical_url": "https://cccultivate.com/product/cook-grow-with-me-payment-plan/",
        "checkout_url": "https://buy.stripe.com/9B6dR81Nb8wc5Sm14PeIw0L",
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "STRIPE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 460,
        "source_authority": "woocommerce_external",
        "aliases": [
            "cook and grow payment plan",
            "cook & grow with me payment plan",
            "dual bundle payment plan",
        ],
    },

    # -------------------------------------------------------------------------
    # LEGENDS NFT MEMBERSHIPS (TORQUE & SIBLINGS)
    # -------------------------------------------------------------------------
    "wnb:nft:torque": {
        "canonical_id": "wnb:nft:torque",
        "entity_type": "NFT_MEMBERSHIP_PARENT",
        "brand": "Wake'n'Bake Lounge",
        "category": ["Membership", "NFT", "Legends"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": None,  # Variable product: tiers $5,000 - $40,000
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Torque - Wake'n'Bake Legends NFT Membership ($5,000 - $40,000).",
        "description": "Torque character tier of the Wake'n'Bake Legends NFT collection. Includes character collectible digital pass, Wake'n'Bake Lounge platform access, and enrollment choice of one structured educational class.",
        "benefits": [
            "Collectible Legends character digital pass",
            "VIP Wake'n'Bake Lounge platform community access",
            "Enrollment in choice of 1 structured course (Grow Cannabis @ Home or Culinary Cannabis)",
            "Exclusive private Discord / Legends channels",
        ],
        "audience": ["NFT collectors", "Cannabis industry patrons", "High-tier patrons"],
        "customer_goals": ["Acquire collectible digital pass and lifetime educational membership"],
        "eligibility_rules": ["21+ and crypto/fiat payment"],
        "exclusions": ["Does not grant equity or securities ownership"],
        "fulfillment_type": "MEMBERSHIP_ACCESS",
        "fulfillment_platform": "WOOCOMMERCE",
        "canonical_url": "https://cccultivate.com/product/torque-nft-membership/",
        "checkout_url": "https://cccultivate.com/product/torque-nft-membership/",
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "WOOCOMMERCE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 875,
        "source_authority": "woocommerce",
        "aliases": [
            "torque",
            "torque nft",
            "torque nft membership",
            "torque legend",
        ],
    },

    "wnb:nft:torque:bronze": {
        "canonical_id": "wnb:nft:torque:bronze",
        "entity_type": "NFT_MEMBERSHIP_TIER",
        "brand": "Wake'n'Bake Lounge",
        "category": ["Membership", "NFT", "Legends", "Bronze"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 5000.0,
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Torque - NFT Membership (Bronze Tier, $5,000).",
        "description": "Bronze tier membership for Torque character in Wake'n'Bake Legends.",
        "benefits": ["Bronze collectible pass", "Lounge access", "Course enrollment choice"],
        "audience": ["Legends patrons"],
        "customer_goals": ["Join Legends at Bronze level"],
        "eligibility_rules": ["21+"],
        "exclusions": [],
        "fulfillment_type": "MEMBERSHIP_ACCESS",
        "fulfillment_platform": "WOOCOMMERCE",
        "canonical_url": "https://cccultivate.com/product/torque-nft-membership/?attribute_membership-tiers=Bronze",
        "checkout_url": "https://cccultivate.com/product/torque-nft-membership/?attribute_membership-tiers=Bronze",
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "WOOCOMMERCE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 877,
        "source_authority": "woocommerce",
        "aliases": ["torque bronze", "bronze torque"],
    },

    "wnb:nft:torque:copper": {
        "canonical_id": "wnb:nft:torque:copper",
        "entity_type": "NFT_MEMBERSHIP_TIER",
        "brand": "Wake'n'Bake Lounge",
        "category": ["Membership", "NFT", "Legends", "Copper"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 10000.0,
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Torque - NFT Membership (Copper Tier, $10,000).",
        "description": "Copper tier membership for Torque character in Wake'n'Bake Legends.",
        "benefits": ["Copper collectible pass", "Lounge access", "Course enrollment choice"],
        "audience": ["Legends patrons"],
        "customer_goals": ["Join Legends at Copper level"],
        "eligibility_rules": ["21+"],
        "exclusions": [],
        "fulfillment_type": "MEMBERSHIP_ACCESS",
        "fulfillment_platform": "WOOCOMMERCE",
        "canonical_url": "https://cccultivate.com/product/torque-nft-membership/?attribute_membership-tiers=Copper",
        "checkout_url": "https://cccultivate.com/product/torque-nft-membership/?attribute_membership-tiers=Copper",
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "WOOCOMMERCE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 878,
        "source_authority": "woocommerce",
        "aliases": ["torque copper", "copper torque"],
    },

    "wnb:nft:torque:titanium": {
        "canonical_id": "wnb:nft:torque:titanium",
        "entity_type": "NFT_MEMBERSHIP_TIER",
        "brand": "Wake'n'Bake Lounge",
        "category": ["Membership", "NFT", "Legends", "Titanium"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 20000.0,
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Torque - NFT Membership (Titanium Tier, $20,000).",
        "description": "Titanium tier membership for Torque character in Wake'n'Bake Legends.",
        "benefits": ["Titanium collectible pass", "VIP Lounge access", "Course enrollment choice"],
        "audience": ["Legends patrons"],
        "customer_goals": ["Join Legends at Titanium level"],
        "eligibility_rules": ["21+"],
        "exclusions": [],
        "fulfillment_type": "MEMBERSHIP_ACCESS",
        "fulfillment_platform": "WOOCOMMERCE",
        "canonical_url": "https://cccultivate.com/product/torque-nft-membership/?attribute_membership-tiers=Titanium",
        "checkout_url": "https://cccultivate.com/product/torque-nft-membership/?attribute_membership-tiers=Titanium",
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "WOOCOMMERCE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 879,
        "source_authority": "woocommerce",
        "aliases": ["torque titanium", "titanium torque"],
    },

    "wnb:nft:torque:platinum": {
        "canonical_id": "wnb:nft:torque:platinum",
        "entity_type": "NFT_MEMBERSHIP_TIER",
        "brand": "Wake'n'Bake Lounge",
        "category": ["Membership", "NFT", "Legends", "Platinum"],
        "approval_status": "OWNER_APPROVED",
        "release_state": "RELEASED",
        "customer_purchasable": True,
        "catalog_visibility": "visible",
        "stock_status": "instock",
        "price_usd": 40000.0,
        "currency": "USD",
        "billing_model": "ONE_TIME",
        "short_summary": "Torque - NFT Membership (Platinum Tier, $40,000).",
        "description": "Platinum tier membership for Torque character in Wake'n'Bake Legends.",
        "benefits": ["Platinum collectible pass", "VIP Lounge access", "Full access package"],
        "audience": ["Legends patrons"],
        "customer_goals": ["Join Legends at top tier Platinum level"],
        "eligibility_rules": ["21+"],
        "exclusions": [],
        "fulfillment_type": "MEMBERSHIP_ACCESS",
        "fulfillment_platform": "WOOCOMMERCE",
        "canonical_url": "https://cccultivate.com/product/torque-nft-membership/?attribute_membership-tiers=Platinum",
        "checkout_url": "https://cccultivate.com/product/torque-nft-membership/?attribute_membership-tiers=Platinum",
        "booking_url": None,
        "payment_plan_available": False,
        "payment_plan_amount": None,
        "payment_plan_url": None,
        "payment_processor": "WOOCOMMERCE",
        "coupon_relationship": None,
        "wix_plan_id": None,
        "wordpress_page_id": 880,
        "source_authority": "woocommerce",
        "aliases": ["torque platinum", "platinum torque"],
    },
}


def get_approved_enrichment(canonical_id: str) -> dict[str, Any] | None:
    """Retrieve approved enrichment dictionary for canonical_id."""
    return APPROVED_ENRICHMENT_REGISTRY.get(canonical_id)


def get_all_approved_aliases() -> dict[str, str]:
    """Build normalized alias -> canonical_id lookup map."""
    alias_map: dict[str, str] = {}
    for canonical_id, data in APPROVED_ENRICHMENT_REGISTRY.items():
        aliases = data.get("aliases", [])
        for alias in aliases:
            norm = alias.strip().lower()
            alias_map[norm] = canonical_id
    return alias_map
