const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const workflow = JSON.parse(fs.readFileSync(path.join(root, 'deploy', 'n8n', 'REV-Woo-Order-Event-Intake-STS2.json'), 'utf8'))[0];
const code = workflow.nodes.find((node) => node.name === 'Normalize Revenue Event v1').parameters.jsCode;
const run = new Function('$json', '$execution', code);
const base = {body:{id:321,number:'321',status:'processing',currency:'USD',total:'19.99',discount_total:'0',shipping_total:'0',total_tax:'0',date_modified_gmt:'2026-09-09T12:00:00',line_items:[{id:9,product_id:101,variation_id:0,sku:'BOOK-BOTANICAL-1',quantity:1,total:'19.99',total_tax:'0'}]},intake:{source_site:'cccultivate.com',topic:'order.updated',event:'updated',webhook_id:'5',delivery_id:'delivery-1',received_at:'2026-09-09T12:00:01Z',n8n_execution_id:'42'},payload_sha256:'a'.repeat(64)};
const attributed=JSON.parse(JSON.stringify(base));
attributed.body.meta_data=[{key:'_budly_commerce_correlation_id',value:'sts2_'+'b'.repeat(32)},{key:'_budly_conversation_id',value:'conv_1234567890abcdef'},{key:'_budly_decision_id',value:'dec_1234567890abcdef'},{key:'billing_email',value:'must-not-cross-boundary@example.com'}];
const linked=run(attributed,{id:'42'}).json;
if(linked.revenue_event.commerce_correlation.status!=='linked')throw new Error('valid correlation not linked');
if(linked.revenue_event.commerce_correlation.correlation_id!=='sts2_'+'b'.repeat(32))throw new Error('correlation ID changed');
if(JSON.stringify(linked).includes('must-not-cross-boundary'))throw new Error('PII crossed normalization boundary');
const unrelated=run(base,{id:'43'}).json;
if(unrelated.revenue_event.commerce_correlation.status!=='absent')throw new Error('unrelated order falsely attributed');
const invalid=JSON.parse(JSON.stringify(base));
invalid.body.meta_data=[{key:'_budly_commerce_correlation_id',value:'customer-supplied'},{key:'_budly_conversation_id',value:'conv_1234567890abcdef'}];
const rejected=run(invalid,{id:'44'}).json;
if(rejected.revenue_event.commerce_correlation.status!=='invalid')throw new Error('invalid correlation not rejected');
if('correlation_id' in rejected.revenue_event.commerce_correlation)throw new Error('invalid correlation propagated');
if(linked.idempotency_identity!==unrelated.idempotency_identity)throw new Error('STS-2 changed idempotency identity');
if(linked.revenue_event.gross_amount!==19.99||linked.revenue_event.currency!=='USD')throw new Error('commercial truth changed');
console.log('STS-2 revenue normalizer runtime tests passed');
