<?php
namespace Budly\SecureMemory\Admin;
use Budly\SecureMemory\Audit\AuditService;use Budly\SecureMemory\Config;use Budly\SecureMemory\Email\EmailTransport;use Budly\SecureMemory\Errors;use Budly\SecureMemory\Sessions\SessionRepository;
if(!defined('ABSPATH')){exit;}
final class AdminService{
 private $repo;private $sessions;private $email;private $audit;public function __construct(AdminRepository $repo,SessionRepository $sessions,EmailTransport $email,AuditService $audit){$this->repo=$repo;$this->sessions=$sessions;$this->email=$email;$this->audit=$audit;}
 public function health(){global $wpdb;$tables=array();foreach(array('customers','verification_requests','sessions','consent','conversation_memory','audit','memory_contexts','idempotency','decision_evidence','rule_configurations','commercial_memory','conversation_contexts') as $name){$tables[$name]=$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',Config::table($name)))===Config::table($name);}$healthy=!in_array(false,$tables,true);return array('status'=>$healthy?'healthy':'degraded','application_version'=>BUDLY_SALES_VERSION,'schema_version'=>get_option('budly_secure_memory_schema_version','not_installed'),'api_version'=>Config::API_VERSION,'bros_rule_version'=>Config::BROS_RULE_VERSION,'active_configurations'=>$this->repo->active_configurations(),'tables'=>$tables,'metrics'=>array('customers'=>$this->repo->count('customers'),'active_sessions'=>$this->repo->count('sessions',"status = 'active'"),'revoked_sessions'=>$this->repo->count('sessions',"status = 'revoked'"),'delivery_failures'=>$this->repo->count('verification_requests',"delivery_status = 'failed'"),'active_memory'=>$this->repo->count('conversation_memory','deleted_at IS NULL'),'active_commercial_memory'=>$this->repo->count('commercial_memory',"status = 'active'"),'conversation_contexts'=>$this->repo->count('conversation_contexts',"status = 'active'")),'last_cleanup'=>get_option('budly_secure_memory_last_cleanup',null));}
 public function decision_evidence(array $filters,$page=1,$per_page=25){$page=max(1,min(10000,(int)$page));$per_page=max(1,min(100,(int)$per_page));return array('items'=>$this->repo->decisions($filters,$page,$per_page),'page'=>$page,'per_page'=>$per_page);}
 public function revoke_session($session_id){$customer=$this->repo->session_customer($session_id);if(!$customer)return array('error'=>Errors::INVALID_REQUEST,'status'=>404,'message'=>'The session was not found.');$count=$this->sessions->revoke($session_id,'administrator',current_time('mysql',true));$this->log('admin.session_revoked',array('session_id'=>$session_id,'affected'=>$count));return array('revoked'=>$count===1,'session_id'=>$session_id);}
 public function revoke_all($public_id){$customer=$this->repo->customer_internal_id($public_id);if(!$customer)return array('error'=>Errors::INVALID_REQUEST,'status'=>404,'message'=>'The customer was not found.');$count=$this->sessions->revoke_all_for_customer((int)$customer,'administrator',current_time('mysql',true));$this->log('admin.customer_sessions_revoked',array('customer_reference'=>$public_id,'affected'=>$count));return array('revoked_count'=>(int)$count,'customer_id'=>$public_id);}
 public function test_email($email){$email=sanitize_email($email);if(!$email||!is_email($email))return array('error'=>Errors::INVALID_EMAIL,'status'=>422,'message'=>'Enter a valid test email address.');$sent=$this->email->send_test($email);$this->log('admin.test_email',array('delivery'=>$sent?'sent':'failed'),$sent?'success':'failure',$sent?'informational':'error');if(!$sent)return array('error'=>Errors::EMAIL_DELIVERY_UNAVAILABLE,'status'=>503,'message'=>'The test email could not be sent.');return array('sent'=>true);}
 public function audit_log(array $filters,$page,$per_page){$rows=$this->repo->audit($filters,max(1,min(10000,$page)),max(1,min(100,$per_page)));foreach($rows as &$row){$row['metadata']=json_decode($row['metadata_json'],true);unset($row['metadata_json']);}unset($row);return array('items'=>$rows,'page'=>$page,'per_page'=>$per_page);}
 private function log($event,array $metadata,$result='success',$severity='warning'){$this->audit->record($event,'administrator',(string)get_current_user_id(),$result,$severity,array('metadata'=>$metadata));}
}
