<?php
namespace Budly\SecureMemory\Cleanup;
use Budly\SecureMemory\Audit\AuditService;use Budly\SecureMemory\Config;use Budly\SecureMemory\Database\Repository;
if(!defined('ABSPATH')){exit;}
final class CleanupService{
 private $wpdb;private $audit;public function __construct($database=null,AuditService $audit=null){if($database!==null)$this->wpdb=$database;else{global $wpdb;$this->wpdb=$wpdb;}$this->audit=$audit?:new AuditService(new Repository($this->wpdb));}
 public static function scheduled_run(){return(new self())->run('scheduler');}
 public function run($source='administrator'){$started=microtime(true);$now=current_time('mysql',true);$verification_cutoff=gmdate('Y-m-d H:i:s',time()-Config::retention_days('verification')*DAY_IN_SECONDS);$session_cutoff=gmdate('Y-m-d H:i:s',time()-Config::retention_days('session')*DAY_IN_SECONDS);$batch=Config::CLEANUP_BATCH_SIZE;$counts=array();try{$counts['verification_requests']=$this->delete_batch('verification_requests','expires_at < %s AND created_at < %s',array($now,$verification_cutoff),$batch);$counts['sessions']=$this->delete_batch('sessions','(status = %s OR absolute_expires_at < %s) AND absolute_expires_at < %s',array('revoked',$now,$session_cutoff),$batch);$counts['memory_contexts']=$this->delete_batch('memory_contexts','expires_at < %s',array($now),$batch);$counts['idempotency']=$this->delete_batch('idempotency','expires_at < %s',array($now),$batch);$summary=array('status'=>'success','source'=>sanitize_key($source),'started_at'=>gmdate('c'),'completed_at'=>gmdate('c'),'duration_ms'=>(int)((microtime(true)-$started)*1000),'deleted'=>$counts,'preserved'=>array('consent'=>true,'consent_history'=>true,'audit'=>true,'customer_memory'=>true));update_option('budly_secure_memory_last_cleanup',$summary,false);$this->audit->record('cleanup.completed',$source==='scheduler'?'system':'administrator',$source==='scheduler'?'scheduler':(string)get_current_user_id(),'success','informational',array('metadata'=>array('deleted'=>$counts,'duration_ms'=>$summary['duration_ms'])));return$summary;}catch(\Throwable $e){$summary=array('status'=>'failure','source'=>sanitize_key($source),'failed_at'=>gmdate('c'),'deleted'=>$counts);update_option('budly_secure_memory_last_cleanup',$summary,false);$this->audit->record('cleanup.failed',$source==='scheduler'?'system':'administrator',$source==='scheduler'?'scheduler':(string)get_current_user_id(),'failure','error',array('metadata'=>array('completed_steps'=>array_keys($counts))));throw$e;}}
 private function delete_batch($logical,$condition,array$args,$limit){$sql='DELETE FROM '.Config::table($logical).' WHERE '.$condition.' LIMIT %d';$args[]=$limit;$result=$this->wpdb->query($this->wpdb->prepare($sql,$args));if($result===false)throw new \RuntimeException('Cleanup step failed.');return(int)$result;}
}
