<?php
namespace Budly\SecureMemory;

if (!defined('ABSPATH')) { exit; }

final class Errors {
    const INVALID_REQUEST = 'INVALID_REQUEST';
    const INVALID_EMAIL = 'INVALID_EMAIL';
    const INVALID_CODE = 'INVALID_CODE';
    const CODE_EXPIRED = 'CODE_EXPIRED';
    const CODE_ALREADY_USED = 'CODE_ALREADY_USED';
    const VERIFICATION_LOCKED = 'VERIFICATION_LOCKED';
    const RATE_LIMITED = 'RATE_LIMITED';
    const EMAIL_DELIVERY_UNAVAILABLE = 'EMAIL_DELIVERY_UNAVAILABLE';
    const AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED';
    const SESSION_INVALID = 'SESSION_INVALID';
    const SESSION_EXPIRED = 'SESSION_EXPIRED';
    const SESSION_REVOKED = 'SESSION_REVOKED';
    const AGENT_NOT_REGISTERED = 'AGENT_NOT_REGISTERED';
    const AGENT_NOT_AUTHORIZED = 'AGENT_NOT_AUTHORIZED';
    const CONSENT_REQUIRED = 'CONSENT_REQUIRED';
    const CONSENT_DENIED = 'CONSENT_DENIED';
    const MEMORY_USE_NOT_APPROVED = 'MEMORY_USE_NOT_APPROVED';
    const MEMORY_NOT_FOUND = 'MEMORY_NOT_FOUND';
    const MEMORY_UNAVAILABLE = 'MEMORY_UNAVAILABLE';
    const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
    const FIELD_NOT_ALLOWED = 'FIELD_NOT_ALLOWED';
    const CONVERSATION_ID_REQUIRED = 'CONVERSATION_ID_REQUIRED';
    const CONVERSATION_NOT_AUTHORIZED = 'CONVERSATION_NOT_AUTHORIZED';
    const RESOURCE_CONFLICT = 'RESOURCE_CONFLICT';
    const CSRF_VALIDATION_FAILED = 'CSRF_VALIDATION_FAILED';
    const ADMIN_PERMISSION_REQUIRED = 'ADMIN_PERMISSION_REQUIRED';
    const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
    const INTERNAL_ERROR = 'INTERNAL_ERROR';
}
