<?php
namespace Budly\Commerce;
use Budly\SecureMemory\Config;
if(!defined('ABSPATH')){exit;}
final class CommerceRepository{
 private $wpdb;public function __construct($database=null){if($database!==null){$this->wpdb=$database;}else{global $wpdb;$this->wpdb=$wpdb;}}
 public function event_by_key($key){return$this->wpdb->get_row($this->wpdb->prepare('SELECT * FROM '.Config::table('commerce_events').' WHERE external_event_key=%s LIMIT 1',$key),ARRAY_A);}
 public function recorded_revenue_event($order_id){return$this->wpdb->get_row($this->wpdb->prepare('SELECT * FROM '.Config::table('commerce_events')." WHERE order_id=%d AND event_type IN ('payment_completed','order_completed') AND verification_status='verified' AND gross_amount>0 ORDER BY id LIMIT 1",(int)$order_id),ARRAY_A);}
 public function recorded_refund_total($order_id){return(string)$this->wpdb->get_var($this->wpdb->prepare('SELECT COALESCE(SUM(refund_amount),0) FROM '.Config::table('commerce_events')." WHERE order_id=%d AND event_type='order_refunded' AND verification_status='verified'",(int)$order_id));}
 public function recorded_net_total($order_id){return(string)$this->wpdb->get_var($this->wpdb->prepare('SELECT COALESCE(SUM(net_amount),0) FROM '.Config::table('commerce_events')." WHERE order_id=%d AND verification_status='verified'",(int)$order_id));}
 public function recorded_commercial_totals($order_id){$row=$this->wpdb->get_row($this->wpdb->prepare('SELECT COALESCE(SUM(gross_amount),0) gross_amount,COALESCE(SUM(discount_amount),0) discount_amount,COALESCE(SUM(shipping_amount),0) shipping_amount,COALESCE(SUM(tax_amount),0) tax_amount FROM '.Config::table('commerce_events')." WHERE order_id=%d AND verification_status='verified'",(int)$order_id),ARRAY_A);return$row?:array('gross_amount'=>'0','discount_amount'=>'0','shipping_amount'=>'0','tax_amount'=>'0');}
 public function insert_event(array $row){$ok=$this->wpdb->insert(Config::table('commerce_events'),$row);if($ok===false)throw new \RuntimeException('Commerce event could not be recorded.');return(int)$this->wpdb->insert_id;}
 public function order_link($order_id){return$this->wpdb->get_row($this->wpdb->prepare('SELECT * FROM '.Config::table('order_links').' WHERE order_id=%d LIMIT 1',(int)$order_id),ARRAY_A);}
 public function save_link(array $row){$existing=$this->order_link($row['order_id']);if($existing){$id=$existing['id'];unset($row['created_at']);$ok=$this->wpdb->update(Config::table('order_links'),$row,array('id'=>$id));}else{$ok=$this->wpdb->insert(Config::table('order_links'),$row);}if($ok===false)throw new \RuntimeException('Order attribution could not be recorded.');return$existing?$existing['link_uuid']:$row['link_uuid'];}
 public function replace_daily(array $row){$where=array('revenue_date'=>$row['revenue_date'],'currency'=>$row['currency'],'product_id'=>$row['product_id'],'affiliate_id'=>$row['affiliate_id']);$existing=$this->wpdb->get_var($this->wpdb->prepare('SELECT id FROM '.Config::table('revenue_daily').' WHERE revenue_date=%s AND currency=%s AND product_id=%d AND affiliate_id=%s LIMIT 1',$row['revenue_date'],$row['currency'],$row['product_id'],$row['affiliate_id']));if($existing){$ok=$this->wpdb->update(Config::table('revenue_daily'),$row,array('id'=>$existing));}else{$ok=$this->wpdb->insert(Config::table('revenue_daily'),$row);}if($ok===false)throw new \RuntimeException('Revenue aggregate could not be recorded.');}
 public function events_for_day($date,$currency){return$this->wpdb->get_results($this->wpdb->prepare('SELECT * FROM '.Config::table('commerce_events').' WHERE DATE(source_occurred_at)=%s AND currency=%s AND verification_status=%s ORDER BY id',$date,$currency,'verified'),ARRAY_A);}
 public function currencies_for_day($date){return$this->wpdb->get_col($this->wpdb->prepare('SELECT DISTINCT currency FROM '.Config::table('commerce_events').' WHERE DATE(source_occurred_at)=%s AND verification_status=%s AND currency IS NOT NULL',$date,'verified'));}
 public function report($from,$to,$currency,$page,$per_page){$offset=($page-1)*$per_page;$sql='SELECT revenue_date,currency,product_id,affiliate_id,orders_count,gross_amount,refund_amount,net_amount,attributed_amount,unattributed_amount,source_event_count,calculated_at FROM '.Config::table('revenue_daily').' WHERE revenue_date BETWEEN %s AND %s';$args=array($from,$to);if($currency){$sql.=' AND currency=%s';$args[]=$currency;}$sql.=' ORDER BY revenue_date DESC,currency,product_id,affiliate_id LIMIT %d OFFSET %d';$args[]=$per_page;$args[]=$offset;return$this->wpdb->get_results($this->wpdb->prepare($sql,$args),ARRAY_A);}
 public function integration_health(){return array('woocommerce_active'=>class_exists('WooCommerce')&&function_exists('wc_get_order'),'last_verified_event'=>$this->wpdb->get_var('SELECT MAX(processed_at) FROM '.Config::table('commerce_events')." WHERE verification_status='verified'"),'pending_reconciliation'=>(int)$this->wpdb->get_var('SELECT COUNT(*) FROM '.Config::table('commerce_events')." WHERE reconciliation_status='pending'"),'conflicts'=>(int)$this->wpdb->get_var('SELECT COUNT(*) FROM '.Config::table('order_links')." WHERE conflict_state<>'none'"));}
}
