<?php
namespace Budly\SecureMemory\Memory;

use Budly\SecureMemory\Audit\AuditService;
use Budly\SecureMemory\Authorization\AgentRegistry;
use Budly\SecureMemory\Config;
use Budly\SecureMemory\Consent\ConsentRepository;
use Budly\SecureMemory\Consent\ConsentService;
use Budly\SecureMemory\Errors;
use Budly\SecureMemory\Profile\ProfileService;
use Budly\SecureMemory\Sessions\SessionService;

if(!defined('ABSPATH')){exit;}

final class MemoryService {
    private $repo;private $consent_repo;private $consent;private $agents;private $profile;private $sessions;private $audit;
    public function __construct(MemoryRepository $repo,ConsentRepository $consent_repo,ConsentService $consent,AgentRegistry $agents,ProfileService $profile,SessionService $sessions,AuditService $audit){$this->repo=$repo;$this->consent_repo=$consent_repo;$this->consent=$consent;$this->agents=$agents;$this->profile=$profile;$this->sessions=$sessions;$this->audit=$audit;}
    public function preview(array $session){$profile=$this->profile->read((int)$session['customer_id']);$rows=$this->repo->visible((int)$session['customer_id'],25);$memories=array();$namespaces=array();foreach($rows as $row){$summary=json_decode($row['summary_json'],true);if(!is_array($summary))continue;$safe=array_intersect_key($summary,array_flip(array('topic','customer_goal','open_questions','next_recommended_step')));$memories[]=array('memory_id'=>$row['memory_id'],'namespace'=>$row['namespace'],'summary'=>$safe,'updated_at'=>gmdate('c',strtotime($row['updated_at'].' UTC')),'expires_at'=>$row['expires_at']?gmdate('c',strtotime($row['expires_at'].' UTC')):null,'retention_policy'=>$row['retention_policy']);$namespaces[$row['namespace']]=true;}$this->audit->record('memory.preview_accessed','customer',(string)$session['customer_id'],'success','informational');return array('has_memory'=>(bool)$memories,'profile'=>array_intersect_key((array)$profile,array_flip(array('preferred_name','experience_level','communication_preferences'))),'memories'=>$memories,'available_namespaces'=>array_keys($namespaces));}
    public function authorize_use(array $session,array $input,$start_fresh=false){$conversation=$this->conversation($input);$agent=isset($input['agent_id'])?sanitize_key($input['agent_id']):'';if(!$conversation||$agent!==$session['agent_id']||!$this->agents->authorize($agent,'memory:read:shared','shared'))return $this->deny(Errors::AGENT_NOT_AUTHORIZED,'The requested memory context is not authorized.',403);$purpose=$start_fresh?'start_fresh':sanitize_key(isset($input['purpose'])?$input['purpose']:'');if(!$start_fresh&&($purpose!=='personalize_product_guidance'||empty($input['approved'])))return $this->deny(Errors::INVALID_REQUEST,'A supported purpose and explicit approval are required.',422);if(!$start_fresh&&!$this->consent->is_granted((int)$session['customer_id'],'memory_use'))return $this->deny(Errors::CONSENT_REQUIRED,'Memory-use consent is required.',403);$now=current_time('mysql',true);$expires=gmdate('Y-m-d H:i:s',min(strtotime($session['absolute_expires_at'].' UTC'),time()+Config::SESSION_IDLE_SECONDS));$this->repo->set_context($session['session_id'],(int)$session['customer_id'],$conversation,$agent,$purpose,!$start_fresh,$start_fresh,$expires,$now);$this->audit->record($start_fresh?'memory.start_fresh':'memory.use_approved','customer',(string)$session['customer_id'],'success','informational',array('conversation_id'=>$conversation,'metadata'=>array('agent_id'=>$agent,'purpose'=>$purpose)));return array('memory_use_approved'=>!$start_fresh,'start_fresh'=>$start_fresh,'conversation_id'=>$conversation,'agent_id'=>$agent,'expires_at'=>gmdate('c',strtotime($expires.' UTC')));}
    public function shared(array $session,$conversation_id,$namespace='shared'){$context=$this->approved_context($session,$conversation_id);if(isset($context['error']))return $context;if(!$this->agents->authorize($session['agent_id'],$namespace==='shared'?'memory:read:shared':'memory:read:agent',$namespace))return $this->deny(Errors::AGENT_NOT_AUTHORIZED,'The agent cannot access this namespace.',403);$rows=$this->repo->visible((int)$session['customer_id'],100);$out=array();foreach($rows as $row){if($row['namespace']!==$namespace)continue;$out[]=array('memory_id'=>$row['memory_id'],'summary'=>json_decode($row['summary_json'],true),'schema_version'=>(int)$row['schema_version'],'updated_at'=>gmdate('c',strtotime($row['updated_at'].' UTC')));}$profile=$namespace==='shared'?$this->profile->read((int)$session['customer_id']):array();return array('namespace'=>$namespace,'profile'=>array_intersect_key((array)$profile,array_flip(array('preferred_name','experience_level','communication_preferences'))),'memory'=>$out);}
    public function store(array $session,array $input){$customer=(int)$session['customer_id'];$consent=$this->consent_repo->granted_record($customer,'memory_storage');if(!$consent)return $this->deny(Errors::CONSENT_REQUIRED,'Memory-storage consent is required.',403);$conversation=$this->conversation($input);$namespace=isset($input['namespace'])?sanitize_key($input['namespace']):'';if(!$conversation||!in_array($namespace,array('shared','sales'),true)||!$this->agents->authorize($session['agent_id'],'memory:write:summary',$namespace))return $this->deny(Errors::AGENT_NOT_AUTHORIZED,'The summary destination is not authorized.',403);$summary=MemoryPolicy::validate_summary(isset($input['summary'])?$input['summary']:null);if($summary===null)return $this->deny(Errors::INVALID_REQUEST,'The summary contains unsupported, oversized, or sensitive content.',422);if($this->repo->active_count($customer)>=Config::MEMORY_MAX_ACTIVE_PER_CUSTOMER&&!$this->repo->has_summary($customer,$conversation,$namespace,$session['agent_id']))return $this->deny(Errors::RESOURCE_CONFLICT,'The memory record limit has been reached.',409);$now=current_time('mysql',true);$expires=gmdate('Y-m-d H:i:s',time()+Config::MEMORY_DEFAULT_RETENTION_DAYS*DAY_IN_SECONDS);$provenance=array('source'=>'conversation_summary_endpoint','source_agent_id'=>$session['agent_id'],'conversation_id'=>$conversation,'session_id'=>$session['session_id'],'schema_version'=>1,'recorded_at'=>gmdate('c'),'customer_corrected'=>false);$stored=$this->repo->store_summary($customer,$conversation,$namespace,$session['agent_id'],$summary,$consent['consent_id'],$provenance,$expires,$now);$this->audit->record('memory.summary_stored','customer',(string)$customer,'success','informational',array('conversation_id'=>$conversation,'metadata'=>array('memory_id'=>$stored['memory_id'],'namespace'=>$namespace,'duplicate'=>$stored['duplicate'])));return array('memory_id'=>$stored['memory_id'],'namespace'=>$namespace,'stored'=>true,'duplicate'=>$stored['duplicate'],'updated_at'=>gmdate('c',strtotime($now.' UTC')),'expires_at'=>gmdate('c',strtotime($expires.' UTC')),'retention_policy'=>'customer_memory_default');}
    public function correct(array $session,$memory_id,array $input){$customer=(int)$session['customer_id'];$record=$this->repo->find_owned($customer,$memory_id);if(!$record)return $this->deny(Errors::MEMORY_NOT_FOUND,'The remembered item was not found.',404);$consent=$this->consent_repo->granted_record($customer,'memory_storage');if(!$consent)return $this->deny(Errors::CONSENT_REQUIRED,'Memory-storage consent is required to save a correction.',403);$summary=MemoryPolicy::validate_summary(isset($input['summary'])?$input['summary']:null);if($summary===null)return $this->deny(Errors::INVALID_REQUEST,'The correction is unsupported, oversized, or sensitive.',422);$now=current_time('mysql',true);$provenance=array('source'=>'customer_correction','source_agent_id'=>$session['agent_id'],'conversation_id'=>$record['conversation_id'],'session_id'=>$session['session_id'],'schema_version'=>1,'recorded_at'=>gmdate('c'),'customer_corrected'=>true);if(!$this->repo->correct($customer,$memory_id,$summary,$consent['consent_id'],$provenance,$now))return $this->deny(Errors::MEMORY_NOT_FOUND,'The remembered item was not found.',404);$this->audit->record('memory.corrected','customer',(string)$customer,'success','informational',array('metadata'=>array('memory_id'=>$memory_id)));return array('memory_id'=>$memory_id,'corrected'=>true,'updated_at'=>gmdate('c',strtotime($now.' UTC')));}
    public function delete_one(array $session,$memory_id,$confirmation){if($confirmation!==true)return $this->deny(Errors::INVALID_REQUEST,'Deletion confirmation is required.',422);$customer=(int)$session['customer_id'];if(!$this->repo->delete_one($customer,$memory_id,current_time('mysql',true)))return $this->deny(Errors::MEMORY_NOT_FOUND,'The remembered item was not found.',404);$this->audit->record('memory.deleted','customer',(string)$customer,'success','informational',array('metadata'=>array('memory_id'=>$memory_id,'scope'=>'selective')));return array('deleted'=>true,'memory_id'=>$memory_id);}
    public function delete_all(array $session,array $input){if(empty($input['confirmation'])||($input['scope']??'')!=='all_customer_memory')return $this->deny(Errors::INVALID_REQUEST,'Explicit delete-all confirmation is required.',422);$customer=(int)$session['customer_id'];$now=current_time('mysql',true);$this->repo->delete_all($customer,$now);$this->sessions->revoke_all_for_customer($customer,'memory_deleted');$this->sessions->clear_cookie();$this->audit->record('memory.deleted','customer',(string)$customer,'success','warning',array('metadata'=>array('scope'=>'all_customer_memory')));return array('deleted'=>true,'sessions_revoked'=>true,'effective_at'=>gmdate('c',strtotime($now.' UTC')));}
    public function export(array $session){$customer=(int)$session['customer_id'];$profile=$this->profile->read($customer);$memory=array();foreach($this->repo->visible($customer,100) as $row){$provenance=json_decode($row['provenance_json'],true);$safe_provenance=array_intersect_key((array)$provenance,array_flip(array('source','source_agent_id','conversation_id','schema_version','recorded_at','customer_corrected')));$memory[]=array('memory_id'=>$row['memory_id'],'namespace'=>$row['namespace'],'memory_type'=>$row['memory_type'],'summary'=>json_decode($row['summary_json'],true),'provenance'=>$safe_provenance,'created_at'=>gmdate('c',strtotime($row['created_at'].' UTC')),'updated_at'=>gmdate('c',strtotime($row['updated_at'].' UTC')),'expires_at'=>$row['expires_at']?gmdate('c',strtotime($row['expires_at'].' UTC')):null,'retention_policy'=>$row['retention_policy']);}$this->audit->record('memory.exported','customer',(string)$customer,'success','informational',array('metadata'=>array('count'=>count($memory))));return array('exported_at'=>gmdate('c'),'profile'=>$profile,'consent'=>$this->consent->read($customer),'memory'=>$memory);}
    private function approved_context(array $session,$conversation){if(!$this->consent->is_granted((int)$session['customer_id'],'memory_use'))return $this->deny(Errors::CONSENT_REQUIRED,'Memory-use consent is required.',403);$context=$this->repo->find_context($session['session_id'],(int)$session['customer_id'],$conversation,$session['agent_id']);if(!$context||!(bool)$context['approved']||(bool)$context['start_fresh']||$context['purpose']!=='personalize_product_guidance')return $this->deny(Errors::MEMORY_USE_NOT_APPROVED,'Memory use is not approved for this conversation.',403);return $context;}
    private function conversation(array $input){$v=isset($input['conversation_id'])?(string)$input['conversation_id']:'';return preg_match('/^conv_[A-Za-z0-9_-]{6,55}$/',$v)?$v:null;}
    private function deny($code,$message,$status){return array('error'=>$code,'message'=>$message,'status'=>$status);}
}
